services:
  handbrake-webui:
    image: ray5378/handbrake-webui-fnapp:${TRIM_APPVER:-latest}
    container_name: handbrake-webui
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${TRIM_PKGVAR}/config:/config
      - ${drive_path:-/vol1}:/drive
    environment:
      - PORT=${TRIM_SERVICE_PORT}
      - CONFIG_DIR=/config
      - NODE_ENV=production
    devices:
      - /dev/dri:/dev/dri