#!/bin/bash

IMAGE_NAME="ray5378/handbrake-webui-fnapp:${TRIM_APPVER:-latest}"

load_docker_image() {
  docker pull "${IMAGE_NAME}" || {
    echo "Failed to pull image ${IMAGE_NAME}" >> "${TRIM_TEMP_LOGFILE}"
    return 1
  }
}

load_docker_image
exit 0
